# Generated by Django 5.2.13 on 2026-04-27 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(db_index=True, max_length=150, unique=True)),
            ],
            options={
                'db_table': 'guestbook_user',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='guestbook.guestuser')),
            ],
            options={
                'db_table': 'guestbook_entry',
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['-created_date'], name='guestbook_e_created_641b50_idx'), models.Index(fields=['user', '-created_date'], name='guestbook_e_user_id_a573c9_idx')],
            },
        ),
    ]
